// <auto-generated />
namespace Sello.Datastore.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EnforceMandatoryFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnforceMandatoryFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201710272141358_EnforceMandatoryFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
